# Generated by Django 4.2.7 on 2024-08-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('SUV', 'Внедорожник'), ('wagon', 'Универсал'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('coupe', 'Купе'), ('cabrio', 'Кабриолет')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(choices=[('rear', 'Задний'), ('front', 'Передний'), ('full', 'Полный')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electro', 'Электро')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('CVT', 'вариатор'), ('robot', 'Робот')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
